on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: true
      with_authelia:
        type: boolean
        required: true
      artifact_name:
        type: string
        required: true
      repo:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  reusable_build:
    timeout-minutes: 20
    runs-on: ${{ inputs.runs_on }}
    env:
      CI: "true"
      ARTIFACT: ${{ inputs.artifact_name }}
      REPO: ${{ inputs.repo }}
    steps:
      - uses: actions/checkout@v4
      - name: execute setup script
        # after checkout, pwd is the root of the repo thats why cd ../
        # When executing script with sudo, by default sudo doesn't pass env vars to script. -E flag solves that
        run: |
          set -ex
          mv setup.sh ../setup.sh
          cd ../
          chmod +x setup.sh
          params=()
          [[ ${{inputs.with_authelia}} == true ]] && params+=(--with-authelia)
          sudo -E ./setup.sh "${params[@]}"
          cd "$REPO"/docker && docker compose up -d

      # docker compose up --wait was failing as some containers were healthy on second attempt. This action retries
      - name: Wait for containers to be healthy
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
          max-retries: 30
          retry-interval: 15
          compose-file: "docker/docker-compose.yml"
          skip-exited: "true"

      - name: Generate tar
        run: |
          set -ex
          cd docker
          docker compose kill &> /dev/null
          cd ../../
          sudo tar --exclude "$REPO/docker/volumes/db/data" --exclude "$REPO/docker/volumes/caddy" -czvf ~/"$ARTIFACT".tar.gz "$REPO" > /dev/null

      - name: Upload generated tarball
        uses: actions/upload-artifact@v4
        # action cannot detect "$ARTIFACT" env var
        with:
          name: ${{ inputs.artifact_name }}
          path: ~/${{ inputs.artifact_name }}.tar.gz
          retention-days: 5
          if-no-files-found: error
