name: Test supabase docker containers

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["docker/**/*", setup.sh]
  pull_request:
    types: [opened, synchronize, reopened] # default behavior
    paths: ["docker/**/*", setup.sh]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-basic-auth:
    strategy:
      matrix:
        os: [ubuntu-latest]
    uses: "./.github/workflows/reusable_exec.yaml"
    with:
      runs_on: ${{matrix.os}}
      artifact_name: "final"
      repo: ${{github.event.repository.name}}

  build-with-authelia:
    strategy:
      matrix:
        os: [ubuntu-latest]
    uses: "./.github/workflows/reusable_exec.yaml"
    with:
      runs_on: ${{matrix.os}}
      with_authelia: true
      artifact_name: "final_with_authelia"
      repo: ${{github.event.repository.name}}

  build-with-authelia-and-redis:
    strategy:
      matrix:
        os: [ubuntu-latest]
    uses: "./.github/workflows/reusable_exec.yaml"
    with:
      runs_on: ${{matrix.os}}
      with_authelia_and_redis: true
      artifact_name: "final_with_authelia_and_redis"
      repo: ${{github.event.repository.name}}
